#ifndef LAS_SCHEDULE_SIZE
#define LAS_SCHEDULE_SIZE 32
#endif

#ifndef LAS_CRITICAL_LAG_MS
#define LAS_CRITICAL_LAG_MS 500
#endif

#ifndef LAS_INTERNAL_CHAR_STR_SIZE_UNIT
#define LAS_INTERNAL_CHAR_STR_SIZE_UNIT 128
#endif


#define ASAP 0
#define ENDLESS_LOOP -1
